spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Automatically creates tables or updates schema structures
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Formats the printed SQL statements nicely in your logs
        format_sql: true
